name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Triangle.sln
      working-directory: ./src
    - name: Build
      run: dotnet build Triangle.sln --no-restore
      working-directory: ./src
    - name: Test
      run: dotnet test Triangle.sln --no-build --verbosity normal
      working-directory: ./src
